# Generated by Django 2.2.2 on 2019-06-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('legion', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('NOVEL', 'Novel'), ('ANTHOLOGY', 'Anthology'), ('NOVELLA', 'Novella')], default='NOVEL', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.TextField(unique=True),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('type', models.CharField(choices=[('EMPEROR', 'The Emperor'), ('SIGILLITE', 'The Sigillite'), ('PRIMARCH', 'Primarch'), ('ASTARTES', 'Astartes')], max_length=20)),
                ('affiliation', models.ManyToManyField(to='core.Affiliation')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='characters',
            field=models.ManyToManyField(to='core.Character'),
        ),
    ]
